# Generated by Django 4.2.3 on 2023-07-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='feature',
            name='image_path',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_legal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
